:version: 1.2.0
:tip-caption: :bulb:
:toc:
:toclevels: 3

= Twitch Follower Checker Benutzerhandbuch

Der Twitch Follower Checker ist ein browserbasiertes Tool, das Ihnen mühelos ermöglicht, neue Follower und Unfollower auf Ihrem Twitch-Kanal zu verfolgen.

== Wie zu verwenden

Dieses Tool ist zugänglich unter https://kagijpn.github.io/twitch-follower-checker/list/[hier].

=== Authentifizierung mit Twitch

Bei Ihrem ersten Besuch klicken Sie auf die Schaltfläche `Authenticate with Twitch`, um sich zu authentifizieren. Die angezeigte Liste entspricht den authentifizierten Benutzern.

=== Follower List

Diese Funktion zeigt eine Liste der Benutzer an, die derzeit Ihren Kanal verfolgen.

==== Benutzerfilterung

Sie können Benutzer filtern, indem Sie in das Suchtextfeld tippen. +
Die Suchparameter beinhalten `Followed At`, `Display Name`, `User Name` und `User ID`. +
Wenn Sie zum Beispiel `2023/05` eingeben, wird der Filter nur diejenigen anzeigen, die Ihnen seit Mai 2023 folgen.

=== Follower Diff List

Diese Liste zeigt neue Follower und Benutzer an, die nicht mehr folgen.

==== Unterschiede bestätigen

Die Unterschiede im Vergleich zur `Follower List` zum Zeitpunkt des `Last checked` Datums werden angezeigt.

Wenn Sie die Schaltfläche `Done check` drücken, wird das Datum von `Last checked` auf die aktuelle Zeit aktualisiert.
[TIP]
Die Schaltfläche `Done check` muss nicht jedes Mal gedrückt werden. Drücken Sie sie, wann immer Sie die Grundliste für die Differenzberechnung aktualisieren möchten. +
Nach der Aktualisierung des `Last checked` Datums ist es ratsam, mit der <<refreshing-lists, Aktualisierung der Listen>> fortzufahren.

[[refreshing-lists]]
=== Listen aktualisieren
Das Drücken der `Refresh Follower Lists` Schaltfläche ermöglicht es Ihnen, die `Follower List` und die `Follower Diff List` auf ihren neuesten Stand zu aktualisieren. +
Die verbleibende Zeit, bis die Schaltfläche `Refresh Follower Lists` erneut gedrückt werden kann, wird unter `Refresh available in` angezeigt. Dies ist eine Maßnahme zur Kontrolle der Häufigkeit von API-Aufrufen in kurzer Zeit aufgrund der link:https://dev.twitch.tv/docs/api/guide/#twitch-rate-limits[Rate Limits], die von der Twitch API festgelegt wurden.

== Mitmachen

Wir freuen uns über Fehlermeldungen, Verbesserungsvorschläge und Vorschläge für neue Funktionen. Diese werden zur Aufnahme in Betracht gezogen. Wenn Sie können, stellen Sie bitte ein https://github.com/KagiJPN/twitch-follower-checker/issues/new[Issue ein].

Ihre Zusammenarbeit ist sehr wertvoll, da wir bestrebt sind, dieses Tool zu verbessern und einfacher zu bedienen! Wenn es etwas gibt, über das Sie uns erreichen möchten, zögern Sie nicht, mich auf meinem https://twitter.com/KagiJPN[Twitter] zu kontaktieren!

== Lizenz

Dieses Projekt steht unter der https://github.com/KagiJPN/twitch-follower-checker/blob/main/LICENSE[Apache License 2.0].
