:version: 1.2.0
:tip-caption: :bulb:
:toc:
:toclevels: 3

= Twitch Follower Checker User Guide

The Twitch Follower Checker is a browser-based tool that effortlessly enables you to track new followers and unfollowers on your Twitch channel.

[%collapsible]
.Other Language Documentation
====
※ 日本の方向けのドキュメントは https://kagijpn.github.io/twitch-follower-checker/jp/[こちら]！ +
※ Dokumente für Menschen in Deutschland sind https://kagijpn.github.io/twitch-follower-checker/de/[hier]! +
※ El documento para hispanohablantes está https://kagijpn.github.io/twitch-follower-checker/es/[aquí]! +
※ Les documents pour les personnes en France sont https://kagijpn.github.io/twitch-follower-checker/fr/[ici]! +
※ 한국 분들을 위한 문서는 https://kagijpn.github.io/twitch-follower-checker/ko/[여기]서 확인할 수 있습니다! +
※ O documento para os brasileiros está https://kagijpn.github.io/twitch-follower-checker/pt/[aqui]! +
※ Документ для русскоговорящих находится https://kagijpn.github.io/twitch-follower-checker/ru/[здесь]!
====

== How to Use

This tool can be accessed from https://kagijpn.github.io/twitch-follower-checker/list/[here].

=== Authenticating with Twitch

On your initial visit, click the `Authenticate with Twitch` button to authenticate. The displayed list will correspond to the authenticated users.

=== Follower List

This feature displays a list of users currently following your channel.

==== User Filtering

You can filter users by typing into the Search textbox. +
The search parameters include `Followed At`, `Display Name`, `User Name`, and `User ID`. +
For instance, typing `2023/05` will filter to show only those who started following you in May 2023.

=== Follower Diff List

This list allows you to investigate new followers and users who have unfollowed. +
The list displays the difference in followers from the date of the `Last checked` to the present.

==== Confirming Differences

When the `Done check` button is pressed, the date of `Last checked` is updated to the current time.
[TIP]
The `Done check` button doesn't need to be pressed every time. Push it whenever you wish to refresh the base list used for the difference calculation. +
After updating the `Last checked` date, it's advisable to proceed to <<refreshing-lists,refresh the lists>>.

[[refreshing-lists]]
=== Refreshing the Lists
Pressing the `Refresh Follower Lists` button allows you to refresh the `Follower List` and `Follower Diff List` to their latest status. +
The time remaining until the `Refresh Follower Lists` button can be pressed again is indicated under `Refresh available in`. This is a measure to control the frequency of API calls in a short period due to the link:https://dev.twitch.tv/docs/api/guide/#twitch-rate-limits[Rate Limits] set by Twitch API.

== Contribute

We welcome bug reports, suggestions for improvements, and proposals for new features. These will be considered for inclusion. If you can, please https://github.com/KagiJPN/twitch-follower-checker/issues/new[raise an issue].

Your cooperation is highly valued as we strive to enhance this tool and make it easier to use! If there's anything else you'd like to reach out to us about, feel free to get in touch with me on https://twitter.com/KagiJPN[my Twitter]!

== License

This project is licensed under the https://github.com/KagiJPN/twitch-follower-checker/blob/main/LICENSE[Apache License 2.0].
