:version: 1.1.0
:tip-caption: :bulb:
:toc:
:toclevels: 3

= Twitch Follower Checker ユーザーガイド

Twitch Follower Checker は、あなたの Twitch チャンネルの新規フォロワーやアンフォローをブラウザ上で簡単に確認できるウェブアプリケーションです。

== 使用方法

このツールは https://kagijpn.github.io/twitch-follower-checker/list/[こちら] から使用できます。

=== Twitch 認証

初回アクセス時には、`Authenticate with Twitch` ボタンをクリックして認証を行ってください。
表示されるリストは認証を行ったユーザーを対象とします。

=== Follower List

現在あなたをチャンネルをフォローしているユーザーの一覧が表示されます。

==== ユーザーフィルタリング

Search テキストボックスに文字を入力することで、ユーザーをフィルタリングすることができます。
検索対象は、`Followed At`, `Display Name`, `User Name`, `User ID` です。 +
例えば、`2023/05` と入力すると、2023 年 5 月にフォローした人に絞り込まれます。

=== Follower Diff List

新規フォロワーとフォロー解除をした人を調べることが出来ます。
一覧には、`Last checked` の日付の時点のフォロワーから現在のフォロワーの差分が表示されます。

==== 差分の確認

`Done check` ボタンを押下すると、`Last checked` の日付が現在の時刻に更新されます。 +
[TIP]
必ずしも `Done check` ボタンを押下する必要はありません。差分の元となるリストを更新したい任意のタイミングで押下してください。 +
`Last checked` が更新されたら、<<refreshing-lists,リストの更新>> を推奨します。

[[refreshing-lists]]
=== リストの更新
`Refresh Follower Lists` ボタンを押下することで、`Follower List` と `Follower Diff List` を最新の状態に更新できます。 +
`Refresh available in` には、次に `Refresh Follower Lists` ボタンが押下可能になるまでの時間が表示されます。これは、Twitch API が link:https://dev.twitch.tv/docs/api/guide/#twitch-rate-limits[Rate Limits] を設けているため、短時間で連続してAPIを呼び出すことを抑制するためです。

== 貢献

バグ報告や改善提案、機能提案などは随時受け付けています。検討した上で取り入れさせていただきます。
https://github.com/KagiJPN/twitch-follower-checker/issues/new[Issue として起票]して頂ければと思います。

より良く、使いやすいツールにアップデートするためにも、ぜひともご協力のほどお願い申し上げます！
その他、何か連絡がある場合は https://twitter.com/KagiJPN[私のツイッター]までお気軽にご連絡ください！

== ライセンス

このプロジェクトは https://github.com/KagiJPN/twitch-follower-checker/blob/main/LICENSE[Apache License 2.0] に準拠してライセンスされています。
