:version: 1.2.0
:tip-caption: :bulb:
:toc:
:toclevels: 3

= Guia do Usuário do Twitch Follower Checker

O Twitch Follower Checker é uma ferramenta baseada em navegador que permite rastrear novos seguidores e quem deixou de seguir o seu canal na Twitch com facilidade.

== Como usar

Esta ferramenta pode ser acessada a partir de https://kagijpn.github.io/twitch-follower-checker/list/[aqui].

=== Autenticando com a Twitch

Na sua primeira visita, clique no botão `Authenticate with Twitch` para autenticar. A lista exibida corresponderá aos usuários autenticados.

=== Follower List

Este recurso exibe uma lista de usuários que estão atualmente seguindo o seu canal.

==== Filtragem de Usuários

Você pode filtrar usuários digitando na caixa de texto Pesquisar. +
Os parâmetros de pesquisa incluem `Followed At`, `Display Name`, `User Name` e `User ID`. +
Por exemplo, digitar `2023/05` filtrará para mostrar apenas aqueles que começaram a seguir você em Maio de 2023.

=== Follower Diff List

Esta lista mostra novos seguidores e usuários que deixaram de seguir.

==== Confirmando Diferenças

As diferenças em comparação com a `Follower List` a partir da data `Last checked` serão exibidas.

Ao clicar no botão `Done check`, a data `Last checked` será atualizada para o momento atual.
[TIP]
O botão `Done check` não precisa ser pressionado todas as vezes. Aperte-o sempre que desejar atualizar a lista base utilizada para o cálculo da diferença. +
Depois de atualizar a data `Last checked`, é aconselhável prosseguir para <<refreshing-lists, atualizar as listas>>.

[[refreshing-lists]]
=== Atualizando as Listas
Pressionar o botão `Refresh Follower Lists` permite atualizar a `Follower List` e a `Follower Diff List` para o seu status mais recente. +
O tempo restante até que o botão `Refresh Follower Lists` possa ser pressionado novamente é indicado em `Refresh available in`. Esta é uma medida para controlar a frequência das chamadas API em um curto período de tempo devido ao link:https://dev.twitch.tv/docs/api/guide/#twitch-rate-limits[Rate Limits] definido pela API da Twitch.

== Contribuir

Recebemos com prazer relatórios de bugs, sugestões de melhorias e propostas de novos recursos. Estes serão considerados para inclusão. Se puder, por favor https://github.com/KagiJPN/twitch-follower-checker/issues/new[levantar um problema].

Sua cooperação é muito valorizada enquanto nos esforçamos para aprimorar esta ferramenta e torná-la mais fácil de usar! Se houver algo mais que você gostaria de entrar em contato conosco, sinta-se à vontade para entrar em contato comigo no https://twitter.com/KagiJPN[o meu Twitter]!

== Licença

Este projeto está licenciado sob a https://github.com/KagiJPN/twitch-follower-checker/blob/main/LICENSE[Licença Apache 2.0].
