:version: 1.1.0
:tip-caption: :bulb:
:toc:
:toclevels: 3

= Руководство пользователя Twitch Follower Checker

Twitch Follower Checker - это инструмент на основе браузера, который без труда позволяет вам отслеживать новых подписчиков и тех, кто отписался от вашего канала Twitch.

== Как использовать

Этот инструмент доступен по адресу https://kagijpn.github.io/twitch-follower-checker/list/[здесь].

=== Аутентификация с Twitch

При первом посещении нажмите кнопку `Authenticate with Twitch`, чтобы выполнить аутентификацию. Отображаемый список будет соответствовать аутентифицированным пользователям.

=== Follower List

Эта функция отображает список пользователей, которые в данный момент подписаны на ваш канал.

==== Фильтрация пользователей

Вы можете фильтровать пользователей, вводя текст в поле поиска. +
Параметры поиска включают `Followed At`, `Display Name`, `User Name` и `User ID`. +
Например, при вводе `2023/05` будут отображаться только те, кто начал следить за вами в мае 2023 года.

=== Follower Diff List

Этот список показывает новых подписчиков и пользователей, которые отписались.

==== Подтверждение различий

Будут отображены различия по сравнению со `Follower List` на дату `Last checked`.

При нажатии кнопки `Done check` дата `Last checked` обновится до текущего времени.
[TIP]
Кнопку `Done check` не нужно нажимать каждый раз. Нажимайте ее, когда вы хотите обновить базовый список, используемый для расчета различий. +
После обновления даты `Last checked` рекомендуется перейти к <<refreshing-lists,обновлению списков>>.

[[refreshing-lists]]
=== Обновление списков
Нажатие кнопки `Refresh Follower Lists` позволяет обновить `Follower List` и `Follower Diff List` до их последнего состояния. +
Оставшееся время до того, как кнопку `Refresh Follower Lists` можно будет нажать снова, указано под `Refresh available in`. Это мера контроля частоты вызовов API за короткий период из-за установленных Twitch API link:https://dev.twitch.tv/docs/api/guide/#twitch-rate-limits[Rate Limits].

== Содействие

Мы приветствуем отчеты об ошибках, предложения по улучшению и предложения новых функций. Они будут рассмотрены для включения. Если вы можете, пожалуйста, https://github.com/KagiJPN/twitch-follower-checker/issues/new[поднимите вопрос].

Мы высоко ценим ваше сотрудничество, стремясь улучшить этот инструмент и сделать его более удобным в использовании! Если есть что-то еще, что вы хотели бы обсудить с нами, не стесняйтесь связаться со мной на https://twitter.com/KagiJPN[моем Twitter]!

== Лицензия

Этот проект лицензирован под https://github.com/KagiJPN/twitch-follower-checker/blob/main/LICENSE[Apache License 2.0].
